### ISSUE TITLE
Generated code fails to compile when using conditionals in complex mode

### ISSUE THREAD

**Issue by IgorBaratta** [FEniCS/ffcx#124]
Generated C code fails to compile in the complex mode when using conditionals.
This is due to the comparison of complex values which cannot be ordered.

UFL file example:
```
element = FiniteElement("Lagrange", interval, 1)
v = TestFunction(element)
f = Coefficient(element)
x = SpatialCoordinate(interval)
c = conditional(le(real(x[0]),  0.025), 1.0, 0.0)
L = c*inner(f, v) * dx
```

Excerpt of the generated integral code containing the error:
```
...
const ufc_scalar_t x_c0 = coordinate_dofs[0] * FE1_C0_Q2[0][iq][0] + coordinate_dofs[1] * FE1_C0_Q2[0][iq][1];
alignas(32) ufc_scalar_t sv2[4];
sv2[0] = creal(x_c0);
sv2[1] = creal(sv2[0]);
sv2[2] = (sv2[1] <= 0.025 ? 1.0 : 0.0) * w0;  // <=
...
```

**Comment by miklos1** [comment]
Related: firedrakeproject/tsfc#171

**Comment by michalhabera** [comment]
Thanks @miklos1 . Indeed, an easy quick fix would be to generate `creal(A) OP creal(B)` for the binary operators `OP` where only real arguments make sense. That would be reasonably safe, since UFL is already checking, that only reals ever enter the operator (as comparison). As mentioned, compiler could hopefully remove unnecessary double creal call.

Other approaches seem more difficult for uflacs, as temporaries are stored into an C array (all elements have same type). That would mean to create a separate arrays for each datatypes and make compiler more type aware.

@IgorBaratta can you try if compilers are removing redundant `creal` in the quick-fix approach? For simple cases it looks optimistic, https://godbolt.org/z/abgBoN
