### ISSUE TITLE
increasing the entropy of the jit hash

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/ffcx#290]
Currently, generated jit files cause a clash under certain circumstances such as change of Python version. For instance upgrading from python3.8 to python3.9, the generated files have the same name (so a new one is not generated) but are not actually compatible so there is runtime failure.  

Discussion at https://github.com/FEniCS/dolfinx/issues/1227 addresses enabling different cache_dirs for different projects (e.g. one project using python3.8, another using python3.9).

But regardless of cache_dir, that discussion favours the idea of increase the entropy of the hash used to identify generated jit files, e.g. seeding the python version into the hash.

There could be a range of different additional parameters worth feeding into the hash. Python version in the first instance, possibly other compilation parameters.

The action would take place in [`compute_signature`](https://github.com/FEniCS/ffcx/blob/cc9064e3971695352ceb59ac64a0cfb4b011d756/ffcx/naming.py#L13) in ffcx/naming.py. The desirable additional elements would want to be added to the `signatures` list at [l.79](https://github.com/FEniCS/ffcx/blob/cc9064e3971695352ceb59ac64a0cfb4b011d756/ffcx/naming.py#L79).

**Comment by michalhabera** [comment]
@drew-parsons Actually, the action needs to take place here (and several similar calls below) https://github.com/FEniCS/ffcx/blob/master/ffcx/codegeneration/jit.py#L148

It already adds extra compiler args, which is good. Do you want to add the python version in these places in a very similar way and make it into PR? More general, any state which would effect the C code generated by CFFI, thus ABI compatibility of compiled `.so` files should be added there. The hash in the filename should be equivalent to the hash of the code in `libffcx_forms_foo.c`.

**Comment by drew-parsons** [comment]
Ah, right. I'll track done some useful parameters to include. Possibly PY_VERSION_HEX from /usr/include/python*/patchlevel.h.
Except we likely want patch level compatibility in the hash, so might be better with just PY_MAJOR_VERSION and PY_MINOR_VERSION.

**Comment by drew-parsons** [comment]
Except jit.py is already python. So, maybe `sys.api_version` + `sys.abiflags`. Will need to look into whether that's better than `sys.version_info`.

**Comment by michalhabera** [comment]
However, in my installation `sys.api_version` returns 1013 for all python version I have (python2.7, python3.8, python3.9).

The most proper way would be to even distinguish FFCx C code and compiled shared libraries wrt. caching. For example, currently we do invoke recompilation (means FFCx compilation as well as gcc compilation) if extra compiler args changed. This is not necessary, since the C code FFCx generated wouldn't change. This is a bit corner-case, since not many users would recompile their forms and mind the extra time for FFCx code generation. So I am just putting it here as a note.

We mainly need to prevent FFCx caching logic from trying to import non-existing `.so`, which happens now, because existing `.c` was found, but the library was compiled for a different python version, so the `.so` file contains `cpython-38`.

**Comment by drew-parsons** [comment]
And `sys.abiflags` is empty on my system.  Sounds like `sys.version_info` is the one to call in.

**Comment by minrk** [comment]
I just encountered this. `sys.get_config_var('SOABI')` is a good start, because it includes info like:

- python major.minor 
- abi flags
- debug or not

This is basically the suffix of the module filename, minus `.so`.

You can check if the file has been compiled for the current Python by checking for the existence of `{module_name}.{get_config_var('EXTSUFFIX')}`, if you want to separate the code-generation cache from the compilation cache.

**Comment by drew-parsons** [comment]
`get_config_var` doesn't work for me though (both python 3.9 and 3.10),
```
> print(sys.get_config_var('SOABI'))

AttributeError: module 'sys' has no attribute 'get_config_var'
```

**Comment by minrk** [comment]
Sorry, it's sysconfig, not sys. Sysconfig is where all of the extension-compilation options live. You can check `python -m sysconfig` if there are any other values in there you might want, such as CFLAGS.  SOABI doesn't, for example, capture the target architecture (arm vs x86_64) on mac.

**Comment by drew-parsons** [comment]
On my system (Debian Linux) SOABI contains the arch
```
> print(sysconfig.get_config_var('SOABI'))
cpython-310-x86_64-linux-gnu
```

**Comment by minrk** [comment]
Yeah, I would expect it to. Not sure why it doesn't on mac. Maybe because mac has universal binaries so one file may contain intel, arm, or both? Wheel tags are able to represent this, so maybe it's just an oversight.

In any case, SOABI should get you most of the way to what you want here, even if it's not complete in every case, it's an easy improvement that solves many likely collisions.
